### ISSUE TITLE
Error converting to bin

### ISSUE THREAD

**Issue by sammyf** [harrisonvanderbyl/rwkv-cpp-cuda#21]
on Archlinux, up to date.

[error.log](https://github.com/harrisonvanderbyl/rwkv-cpp-cuda/files/11354579/error.log)

**Comment by harrisonvanderbyl** [comment]
Ahh, that happens sometimes

Add #include <ofstream> to the top of the converter cpp file
I'll fix it on the repo in the morning

**Comment by sammyf** [comment]
actually, it's 

#include <fstream>

You got me confused for a bit here;)
That worked, thanks!
