### ISSUE TITLE
Endless <|endoftext|> bug

### ISSUE THREAD

**Issue by Murugurugan** [harrisonvanderbyl/rwkv-cpp-cuda#4]
I am not sure if it's a problem with tokenizer or what, but after model loads, it just spams <|endoftext|> endlessly. That's with 4090 and RWKV v10 7B running on Ubuntu. Doesn't matter what I put in the prompt.

**Comment by harrisonvanderbyl** [comment]
I havent tested it with 7B plus yet, though it should work, please try changing the batching sizes at the top of rwkv.cu and let me know if anything changes.

I am also currently working on a better sampler, as I am currently just using greedy

**Comment by howard0su** [comment]
I have the same problem.

**Comment by harrisonvanderbyl** [comment]
this should be resolved in the latest version, can you confirm there is still issues with 7B ?

**Comment by harrisonvanderbyl** [comment]
that error has been fixed for 7B
